### ISSUE TITLE
error: Creation method of abstract class cannot be public.

### ISSUE THREAD

**Issue by ilya-fedin** [AyatanaIndicators/ayatana-indicator-sound#4]
```
/home/ilya/.cache/yay/ayatana-indicator-sound/src/ayatana-indicator-sound/src/notification.vala:22.2-22.20: error: Creation method of abstract class cannot be public.
	public Notification () {
	^^^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
make[2]: *** [src/CMakeFiles/indicator-sound-service-lib.dir/build.make:277: src/notification.vapi] Ошибка 1
make[2]: *** Ожидание завершения заданий…
/home/ilya/.cache/yay/ayatana-indicator-sound/src/ayatana-indicator-sound/src/notification.vala:22.2-22.20: error: Creation method of abstract class cannot be public.
	public Notification () {
	^^^^^^^^^^^^^^^^^^^
```
Arch Linux, Vala 0.46.5

**Comment by tari01** [comment]
The current version of ayatana-indicator-sound builds on Arch with Vala 0.48.9, so I'm closing this.

**Comment by ilya-fedin** [comment]
Wow, thanks
